---
title: 'rOpenSci Statistical Software Review: Prelminary Empirical Explorations'
author: 'Noam Ross and Mark Padgham'
date: '`r Sys.Date()`'
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: no
    theme: flatly
bibliography: statsoft.bib
---

```{r getbib, include = FALSE, eval = TRUE}
if (!file.exists ("statsoft.bib")) {
   refs <- RefManageR::ReadZotero(group = "2416765",
                                 .params = list (limit = 100))
   RefManageR::WriteBib(refs, "statsoft.bib")
}
```

This repository holds results from a number of preliminary empirical
explorations used to inform and define the scope of rOpenSci's project to
expand peer review to include explicitly statistical software. The project
itself is documented in the [`statistical-software-review-book`
repository](https://github.com/ropenscilabs/statistical-software-review-book),
with this repository serving as a record of some of the empirical explorations
that informed and guided the scope of the project.

Empirical data included a list of the descriptions of [all packages rejected by
rOpenSci](https://github.com/ropenscilabs/statistical-software/blob/master/abstracts/ropensci-abstracts.md)
as being out of current scope because of current inability to consider
statistical packages, along with a selection of [recent statistical
R packages](https://github.com/ropenscilabs/statistical-software/blob/master/abstracts/joss-abstracts.md)
accepted by JOSS. (The full list of all R package published by JOSS can be
viewed at <https://joss.theoj.org/papers//in/R>).

Much of the primary categorization of statistical software was derived from
analyses of all abstracts submitted to Joint Statistical Meetings 2018--2019,
and Symposia on Data Science and Statistics 2018--2020. An example of how this
was done is given in the [`categories.md`
document](https://github.com/ropenscilabs/statistical-software/blob/master/categories.Rmd),
with further detail in
[`abstracts/categories.Rmd`](https://github.com/ropenscilabs/statistical-software/blob/master/abstracts/categories.Rmd).
These empirical analyses were used to construct network relationships between
terms described statistical software, as well as between different kinds of
input and outputs used in statistical software. These network relationships can
be viewed as interactive visualizations via the following links:

1. A concept map on software [testing and
   validation](https://ropenscilabs.github.io/statistical-software/testing-and-validation/).
2. A map between [all forms of data input and corresponding forms of data
   output](https://ropenscilabs.github.io/statistical-software/abstracts/network-io/)
   as processed by all statistical software published by the Journal of Open
   Source Software.
3. A network diagram of [connections between statistical
   terms](https://ropenscilabs.github.io/statistical-software/abstracts/network-terms/)
   in all abstracts of statistical papers published in the Journal of Open
   Source Software.

