var
   GREEN = "rgba(0,255,150,0.8)",
   RED = "rgba(255,50,0,0.8)",
   BLUE = "rgba(0,150,255,0.8)",
   ORANGE = "orange";


var nodes = new vis.DataSet([
    { id: 1,
      value: 2,
      label: "aggregation" },
    { id: 2,
      value: 1,
      label: "algorithm choice" },
    { id: 3,
      value: 1,
      label: "ANCOVA" },
    { id: 4,
      value: 1,
      label: "applied statistics" },
    { id: 5,
      value: 1,
      label: "areal statistics" },
    { id: 6,
      value: 7,
      label: "Bayesian" },
    { id: 7,
      value: 1,
      label: "benchmarking" },
    { id: 8,
      value: 1,
      label: "bias" },
    { id: 9,
      value: 7,
      label: "categorical variables" },
    { id: 10,
      value: 1,
      label: "chronology" },
    { id: 11,
      value: 3,
      label: "clustering" },
    { id: 12,
      value: 1,
      label: "confidence intervals" },
    { id: 13,
      value: 2,
      label: "correlation" },
    { id: 14,
      value: 1,
      label: "covariance" },
    { id: 15,
      value: 2,
      label: "covariates" },
    { id: 16,
      value: 2,
      label: "cross-validation" },
    { id: 17,
      value: 1,
      label: "data preparation" },
    { id: 18,
      value: 1,
      label: "data transformation" },
    { id: 19,
      value: 2,
      label: "density estimator" },
    { id: 20,
      value: 1,
      label: "descriptive statistics" },
    { id: 21,
      value: 1,
      label: "differential equations" },
    { id: 22,
      value: 9,
      label: "dimensionality reduction" },
    { id: 23,
      value: 3,
      label: "discrete data" },
    { id: 24,
      value: 2,
      label: "distance metrics" },
    { id: 25,
      value: 1,
      label: "dynamical systems" },
    { id: 26,
      value: 7,
      label: "EDA" },
    { id: 27,
      value: 4,
      label: "education" },
    { id: 28,
      value: 2,
      label: "effect sizes" },
    { id: 29,
      value: 1,
      label: "error estimates" },
    { id: 30,
      value: 8,
      label: "estimates" },
    { id: 31,
      value: 1,
      label: "factor analysis" },
    { id: 32,
      value: 4,
      label: "feature selection" },
    { id: 33,
      value: 1,
      label: "focal windows" },
    { id: 34,
      value: 3,
      label: "functional data analysis" },
    { id: 35,
      value: 1,
      label: "graphical output" },
    { id: 36,
      value: 1,
      label: "grouped data" },
    { id: 37,
      value: 2,
      label: "high-dimensional data" },
    { id: 38,
      value: 1,
      label: "histograms" },
    { id: 39,
      value: 4,
      label: "index" },
    { id: 40,
      value: 3,
      label: "inference" },
    { id: 41,
      value: 2,
      label: "information statistics" },
    { id: 42,
      value: 1,
      label: "interaction terms" },
    { id: 43,
      value: 4,
      label: "kernel density" },
    { id: 44,
      value: 1,
      label: "kernel logistic regression" },
    { id: 45,
      value: 2,
      label: "latent variables" },
    { id: 46,
      value: 1,
      label: "learning curve" },
    { id: 47,
      value: 3,
      label: "likelihood" },
    { id: 48,
      value: 1,
      label: "marginal effects" },
    { id: 49,
      value: 2,
      label: "matrix algebra" },
    { id: 50,
      value: 1,
      label: "maximum entropy" },
    { id: 51,
      value: 4,
      label: "maximum likelihood" },
    { id: 52,
      value: 1,
      label: "missing value processing" },
    { id: 53,
      value: 12,
      label: "ML" },
    { id: 54,
      value: 1,
      label: "model probability" },
    { id: 55,
      value: 4,
      label: "model selection" },
    { id: 56,
      value: 1,
      label: "model strategy" },
    { id: 57,
      value: 8,
      label: "Monte Carlo" },
    { id: 58,
      value: 1,
      label: "multi-state model" },
    { id: 59,
      value: 1,
      label: "multidimensional model" },
    { id: 60,
      value: 7,
      label: "networks" },
    { id: 61,
      value: 1,
      label: "neural network" },
    { id: 62,
      value: 1,
      label: "noise" },
    { id: 63,
      value: 1,
      label: "non-parametric" },
    { id: 64,
      value: 2,
      label: "non-stationarity" },
    { id: 65,
      value: 1,
      label: "null-hypothesis testing" },
    { id: 66,
      value: 3,
      label: "optimization" },
    { id: 67,
      value: 1,
      label: "ordered response data" },
    { id: 68,
      value: 1,
      label: "outlier detection" },
    { id: 69,
      value: 1,
      label: "overlap" },
    { id: 70,
      value: 1,
      label: "pairwise comparisons" },
    { id: 71,
      value: 1,
      label: "parameter estimation" },
    { id: 72,
      value: 4,
      label: "probability density" },
    { id: 73,
      value: 9,
      label: "probability distributions" },
    { id: 74,
      value: 2,
      label: "random forests" },
    { id: 75,
      value: 1,
      label: "redistribution" },
    { id: 76,
      value: 9,
      label: "regression" },
    { id: 77,
      value: 1,
      label: "reinforcement" },
    { id: 78,
      value: 2,
      label: "reporting" },
    { id: 79,
      value: 2,
      label: "risk" },
    { id: 80,
      value: 4,
      label: "sampling" },
    { id: 81,
      value: 10,
      label: "scores" },
    { id: 82,
      value: 1,
      label: "sensitivity" },
    { id: 83,
      value: 2,
      label: "similarity statistics" },
    { id: 84,
      value: 1,
      label: "simulation" },
    { id: 85,
      value: 3,
      label: "spatial" },
    { id: 86,
      value: 2,
      label: "splines" },
    { id: 87,
      value: 1,
      label: "standard error" },
    { id: 88,
      value: 1,
      label: "stationarity" },
    { id: 89,
      value: 1,
      label: "statistical models" },
    { id: 90,
      value: 6,
      label: "summary statistics" },
    { id: 91,
      value: 6,
      label: "survival" },
    { id: 92,
      value: 2,
      label: "synthetic data" },
    { id: 93,
      value: 1,
      label: "test selection" },
    { id: 94,
      value: 1,
      label: "threshold" },
    { id: 95,
      value: 3,
      label: "time series" },
    { id: 96,
      value: 2,
      label: "trees" },
    { id: 97,
      value: 1,
      label: "uncertainty" },
    { id: 98,
      value: 1,
      label: "variable selection" },
    { id: 99,
      value: 4,
      label: "variance" },
    { id: 100,
      value: 10,
      label: "visualization" },
    { id: 101,
      value: 2,
      label: "warping" },
    { id: 102,
      value: 6,
      label: "workflow" },
    { id: 103,
      value: 9,
      label: "wrapper" }
]);



var edges = new vis.DataSet([
    { from: 1,
      to: 6,
      value: 1 },
    { from: 1,
      to: 30,
      value: 1 },
    { from: 1,
      to: 46,
      value: 1 },
    { from: 1,
      to: 57,
      value: 1 },
    { from: 1,
      to: 75,
      value: 1 },
    { from: 1,
      to: 81,
      value: 2 },
    { from: 1,
      to: 94,
      value: 1 },
    { from: 1,
      to: 97,
      value: 1 },
    { from: 2,
      to: 89,
      value: 1 },
    { from: 2,
      to: 90,
      value: 1 },
    { from: 3,
      to: 13,
      value: 1 },
    { from: 4,
      to: 10,
      value: 1 },
    { from: 4,
      to: 23,
      value: 1 },
    { from: 4,
      to: 39,
      value: 1 },
    { from: 5,
      to: 33,
      value: 1 },
    { from: 5,
      to: 43,
      value: 1 },
    { from: 5,
      to: 44,
      value: 1 },
    { from: 5,
      to: 83,
      value: 1 },
    { from: 5,
      to: 85,
      value: 1 },
    { from: 6,
      to: 26,
      value: 2 },
    { from: 6,
      to: 27,
      value: 1 },
    { from: 6,
      to: 34,
      value: 1 },
    { from: 6,
      to: 47,
      value: 1 },
    { from: 6,
      to: 53,
      value: 1 },
    { from: 6,
      to: 55,
      value: 1 },
    { from: 6,
      to: 57,
      value: 3 },
    { from: 6,
      to: 60,
      value: 1 },
    { from: 6,
      to: 65,
      value: 1 },
    { from: 6,
      to: 75,
      value: 1 },
    { from: 6,
      to: 81,
      value: 1 },
    { from: 6,
      to: 91,
      value: 1 },
    { from: 6,
      to: 94,
      value: 1 },
    { from: 6,
      to: 97,
      value: 1 },
    { from: 6,
      to: 103,
      value: 3 },
    { from: 7,
      to: 60,
      value: 1 },
    { from: 7,
      to: 66,
      value: 1 },
    { from: 8,
      to: 30,
      value: 1 },
    { from: 8,
      to: 72,
      value: 1 },
    { from: 8,
      to: 73,
      value: 1 },
    { from: 8,
      to: 80,
      value: 1 },
    { from: 9,
      to: 17,
      value: 1 },
    { from: 9,
      to: 29,
      value: 1 },
    { from: 9,
      to: 30,
      value: 2 },
    { from: 9,
      to: 39,
      value: 1 },
    { from: 9,
      to: 45,
      value: 1 },
    { from: 9,
      to: 51,
      value: 1 },
    { from: 9,
      to: 52,
      value: 1 },
    { from: 9,
      to: 53,
      value: 1 },
    { from: 9,
      to: 54,
      value: 1 },
    { from: 9,
      to: 60,
      value: 1 },
    { from: 9,
      to: 70,
      value: 1 },
    { from: 9,
      to: 81,
      value: 4 },
    { from: 9,
      to: 96,
      value: 1 },
    { from: 10,
      to: 23,
      value: 1 },
    { from: 10,
      to: 39,
      value: 1 },
    { from: 11,
      to: 22,
      value: 1 },
    { from: 11,
      to: 57,
      value: 1 },
    { from: 11,
      to: 76,
      value: 1 },
    { from: 11,
      to: 79,
      value: 1 },
    { from: 11,
      to: 85,
      value: 1 },
    { from: 12,
      to: 41,
      value: 1 },
    { from: 12,
      to: 51,
      value: 1 },
    { from: 12,
      to: 73,
      value: 1 },
    { from: 13,
      to: 99,
      value: 1 },
    { from: 13,
      to: 103,
      value: 1 },
    { from: 14,
      to: 79,
      value: 1 },
    { from: 14,
      to: 99,
      value: 1 },
    { from: 15,
      to: 26,
      value: 1 },
    { from: 15,
      to: 66,
      value: 1 },
    { from: 15,
      to: 74,
      value: 1 },
    { from: 15,
      to: 96,
      value: 1 },
    { from: 15,
      to: 103,
      value: 1 },
    { from: 16,
      to: 47,
      value: 1 },
    { from: 16,
      to: 53,
      value: 1 },
    { from: 16,
      to: 55,
      value: 1 },
    { from: 17,
      to: 52,
      value: 1 },
    { from: 17,
      to: 53,
      value: 1 },
    { from: 18,
      to: 100,
      value: 1 },
    { from: 18,
      to: 102,
      value: 1 },
    { from: 19,
      to: 26,
      value: 1 },
    { from: 19,
      to: 43,
      value: 2 },
    { from: 19,
      to: 51,
      value: 1 },
    { from: 19,
      to: 63,
      value: 1 },
    { from: 19,
      to: 72,
      value: 1 },
    { from: 19,
      to: 73,
      value: 1 },
    { from: 20,
      to: 26,
      value: 1 },
    { from: 20,
      to: 41,
      value: 1 },
    { from: 20,
      to: 90,
      value: 1 },
    { from: 20,
      to: 98,
      value: 1 },
    { from: 20,
      to: 102,
      value: 1 },
    { from: 21,
      to: 25,
      value: 1 },
    { from: 21,
      to: 40,
      value: 1 },
    { from: 21,
      to: 47,
      value: 1 },
    { from: 22,
      to: 28,
      value: 1 },
    { from: 22,
      to: 32,
      value: 3 },
    { from: 22,
      to: 34,
      value: 1 },
    { from: 22,
      to: 40,
      value: 1 },
    { from: 22,
      to: 53,
      value: 1 },
    { from: 22,
      to: 57,
      value: 1 },
    { from: 22,
      to: 61,
      value: 1 },
    { from: 22,
      to: 74,
      value: 1 },
    { from: 22,
      to: 76,
      value: 1 },
    { from: 22,
      to: 79,
      value: 1 },
    { from: 22,
      to: 80,
      value: 1 },
    { from: 22,
      to: 85,
      value: 1 },
    { from: 22,
      to: 86,
      value: 1 },
    { from: 22,
      to: 91,
      value: 1 },
    { from: 22,
      to: 95,
      value: 1 },
    { from: 22,
      to: 100,
      value: 1 },
    { from: 22,
      to: 102,
      value: 1 },
    { from: 23,
      to: 39,
      value: 1 },
    { from: 23,
      to: 58,
      value: 1 },
    { from: 23,
      to: 67,
      value: 1 },
    { from: 23,
      to: 78,
      value: 1 },
    { from: 23,
      to: 90,
      value: 1 },
    { from: 23,
      to: 91,
      value: 1 },
    { from: 24,
      to: 53,
      value: 1 },
    { from: 24,
      to: 83,
      value: 1 },
    { from: 25,
      to: 40,
      value: 1 },
    { from: 25,
      to: 47,
      value: 1 },
    { from: 26,
      to: 27,
      value: 2 },
    { from: 26,
      to: 31,
      value: 1 },
    { from: 26,
      to: 41,
      value: 1 },
    { from: 26,
      to: 43,
      value: 1 },
    { from: 26,
      to: 53,
      value: 2 },
    { from: 26,
      to: 55,
      value: 1 },
    { from: 26,
      to: 60,
      value: 1 },
    { from: 26,
      to: 74,
      value: 1 },
    { from: 26,
      to: 90,
      value: 1 },
    { from: 26,
      to: 96,
      value: 1 },
    { from: 26,
      to: 98,
      value: 1 },
    { from: 26,
      to: 100,
      value: 2 },
    { from: 26,
      to: 102,
      value: 2 },
    { from: 26,
      to: 103,
      value: 3 },
    { from: 27,
      to: 32,
      value: 1 },
    { from: 27,
      to: 35,
      value: 1 },
    { from: 27,
      to: 53,
      value: 4 },
    { from: 27,
      to: 60,
      value: 1 },
    { from: 27,
      to: 90,
      value: 1 },
    { from: 27,
      to: 100,
      value: 2 },
    { from: 27,
      to: 102,
      value: 1 },
    { from: 27,
      to: 103,
      value: 1 },
    { from: 28,
      to: 40,
      value: 2 },
    { from: 28,
      to: 93,
      value: 1 },
    { from: 29,
      to: 30,
      value: 1 },
    { from: 29,
      to: 81,
      value: 1 },
    { from: 30,
      to: 46,
      value: 1 },
    { from: 30,
      to: 51,
      value: 1 },
    { from: 30,
      to: 57,
      value: 1 },
    { from: 30,
      to: 64,
      value: 1 },
    { from: 30,
      to: 72,
      value: 2 },
    { from: 30,
      to: 73,
      value: 2 },
    { from: 30,
      to: 80,
      value: 1 },
    { from: 30,
      to: 81,
      value: 3 },
    { from: 30,
      to: 84,
      value: 1 },
    { from: 30,
      to: 87,
      value: 1 },
    { from: 30,
      to: 90,
      value: 1 },
    { from: 30,
      to: 91,
      value: 1 },
    { from: 30,
      to: 103,
      value: 1 },
    { from: 31,
      to: 100,
      value: 1 },
    { from: 32,
      to: 34,
      value: 1 },
    { from: 32,
      to: 53,
      value: 1 },
    { from: 32,
      to: 76,
      value: 1 },
    { from: 32,
      to: 86,
      value: 1 },
    { from: 32,
      to: 91,
      value: 1 },
    { from: 32,
      to: 95,
      value: 1 },
    { from: 32,
      to: 100,
      value: 2 },
    { from: 32,
      to: 102,
      value: 1 },
    { from: 33,
      to: 43,
      value: 1 },
    { from: 33,
      to: 44,
      value: 1 },
    { from: 33,
      to: 83,
      value: 1 },
    { from: 33,
      to: 85,
      value: 1 },
    { from: 34,
      to: 76,
      value: 2 },
    { from: 34,
      to: 86,
      value: 1 },
    { from: 34,
      to: 91,
      value: 1 },
    { from: 34,
      to: 100,
      value: 1 },
    { from: 34,
      to: 101,
      value: 1 },
    { from: 35,
      to: 53,
      value: 1 },
    { from: 35,
      to: 90,
      value: 1 },
    { from: 36,
      to: 38,
      value: 1 },
    { from: 36,
      to: 45,
      value: 1 },
    { from: 36,
      to: 76,
      value: 1 },
    { from: 37,
      to: 60,
      value: 1 },
    { from: 37,
      to: 68,
      value: 1 },
    { from: 37,
      to: 76,
      value: 1 },
    { from: 38,
      to: 45,
      value: 1 },
    { from: 38,
      to: 76,
      value: 1 },
    { from: 39,
      to: 69,
      value: 1 },
    { from: 39,
      to: 81,
      value: 2 },
    { from: 39,
      to: 100,
      value: 1 },
    { from: 40,
      to: 47,
      value: 1 },
    { from: 40,
      to: 93,
      value: 1 },
    { from: 41,
      to: 51,
      value: 1 },
    { from: 41,
      to: 73,
      value: 1 },
    { from: 41,
      to: 90,
      value: 1 },
    { from: 41,
      to: 98,
      value: 1 },
    { from: 41,
      to: 102,
      value: 1 },
    { from: 42,
      to: 48,
      value: 1 },
    { from: 42,
      to: 76,
      value: 1 },
    { from: 42,
      to: 100,
      value: 1 },
    { from: 43,
      to: 44,
      value: 1 },
    { from: 43,
      to: 51,
      value: 1 },
    { from: 43,
      to: 63,
      value: 1 },
    { from: 43,
      to: 72,
      value: 1 },
    { from: 43,
      to: 73,
      value: 2 },
    { from: 43,
      to: 83,
      value: 1 },
    { from: 43,
      to: 85,
      value: 1 },
    { from: 44,
      to: 83,
      value: 1 },
    { from: 44,
      to: 85,
      value: 1 },
    { from: 45,
      to: 54,
      value: 1 },
    { from: 45,
      to: 70,
      value: 1 },
    { from: 45,
      to: 76,
      value: 1 },
    { from: 45,
      to: 81,
      value: 1 },
    { from: 46,
      to: 81,
      value: 1 },
    { from: 47,
      to: 55,
      value: 1 },
    { from: 47,
      to: 57,
      value: 1 },
    { from: 47,
      to: 103,
      value: 1 },
    { from: 48,
      to: 76,
      value: 1 },
    { from: 48,
      to: 100,
      value: 1 },
    { from: 49,
      to: 53,
      value: 1 },
    { from: 49,
      to: 72,
      value: 1 },
    { from: 49,
      to: 73,
      value: 1 },
    { from: 49,
      to: 81,
      value: 1 },
    { from: 49,
      to: 82,
      value: 1 },
    { from: 50,
      to: 60,
      value: 1 },
    { from: 51,
      to: 60,
      value: 1 },
    { from: 51,
      to: 63,
      value: 1 },
    { from: 51,
      to: 72,
      value: 2 },
    { from: 51,
      to: 73,
      value: 3 },
    { from: 51,
      to: 96,
      value: 1 },
    { from: 52,
      to: 53,
      value: 1 },
    { from: 53,
      to: 55,
      value: 1 },
    { from: 53,
      to: 56,
      value: 1 },
    { from: 53,
      to: 60,
      value: 1 },
    { from: 53,
      to: 61,
      value: 1 },
    { from: 53,
      to: 72,
      value: 1 },
    { from: 53,
      to: 73,
      value: 1 },
    { from: 53,
      to: 76,
      value: 1 },
    { from: 53,
      to: 77,
      value: 1 },
    { from: 53,
      to: 80,
      value: 1 },
    { from: 53,
      to: 90,
      value: 1 },
    { from: 53,
      to: 91,
      value: 1 },
    { from: 53,
      to: 100,
      value: 3 },
    { from: 53,
      to: 102,
      value: 2 },
    { from: 53,
      to: 103,
      value: 2 },
    { from: 54,
      to: 70,
      value: 1 },
    { from: 54,
      to: 81,
      value: 1 },
    { from: 55,
      to: 76,
      value: 1 },
    { from: 55,
      to: 78,
      value: 1 },
    { from: 55,
      to: 81,
      value: 1 },
    { from: 55,
      to: 91,
      value: 1 },
    { from: 55,
      to: 100,
      value: 1 },
    { from: 55,
      to: 102,
      value: 1 },
    { from: 55,
      to: 103,
      value: 1 },
    { from: 56,
      to: 77,
      value: 1 },
    { from: 56,
      to: 80,
      value: 1 },
    { from: 57,
      to: 75,
      value: 1 },
    { from: 57,
      to: 76,
      value: 1 },
    { from: 57,
      to: 80,
      value: 1 },
    { from: 57,
      to: 81,
      value: 1 },
    { from: 57,
      to: 84,
      value: 1 },
    { from: 57,
      to: 85,
      value: 1 },
    { from: 57,
      to: 90,
      value: 2 },
    { from: 57,
      to: 91,
      value: 1 },
    { from: 57,
      to: 94,
      value: 1 },
    { from: 57,
      to: 97,
      value: 1 },
    { from: 57,
      to: 100,
      value: 1 },
    { from: 57,
      to: 103,
      value: 4 },
    { from: 58,
      to: 91,
      value: 1 },
    { from: 59,
      to: 71,
      value: 1 },
    { from: 59,
      to: 76,
      value: 1 },
    { from: 59,
      to: 86,
      value: 1 },
    { from: 59,
      to: 91,
      value: 1 },
    { from: 60,
      to: 66,
      value: 2 },
    { from: 60,
      to: 68,
      value: 1 },
    { from: 60,
      to: 88,
      value: 1 },
    { from: 60,
      to: 96,
      value: 1 },
    { from: 60,
      to: 100,
      value: 1 },
    { from: 60,
      to: 103,
      value: 1 },
    { from: 62,
      to: 99,
      value: 1 },
    { from: 63,
      to: 72,
      value: 1 },
    { from: 63,
      to: 73,
      value: 1 },
    { from: 64,
      to: 91,
      value: 1 },
    { from: 64,
      to: 95,
      value: 1 },
    { from: 67,
      to: 78,
      value: 1 },
    { from: 67,
      to: 90,
      value: 1 },
    { from: 69,
      to: 81,
      value: 1 },
    { from: 69,
      to: 100,
      value: 1 },
    { from: 70,
      to: 81,
      value: 1 },
    { from: 71,
      to: 76,
      value: 1 },
    { from: 71,
      to: 86,
      value: 1 },
    { from: 71,
      to: 91,
      value: 1 },
    { from: 72,
      to: 73,
      value: 4 },
    { from: 72,
      to: 80,
      value: 1 },
    { from: 73,
      to: 76,
      value: 1 },
    { from: 73,
      to: 80,
      value: 2 },
    { from: 73,
      to: 92,
      value: 1 },
    { from: 74,
      to: 96,
      value: 1 },
    { from: 74,
      to: 103,
      value: 1 },
    { from: 75,
      to: 81,
      value: 1 },
    { from: 75,
      to: 94,
      value: 1 },
    { from: 75,
      to: 97,
      value: 1 },
    { from: 76,
      to: 86,
      value: 2 },
    { from: 76,
      to: 91,
      value: 3 },
    { from: 76,
      to: 100,
      value: 3 },
    { from: 76,
      to: 101,
      value: 1 },
    { from: 77,
      to: 80,
      value: 1 },
    { from: 78,
      to: 81,
      value: 1 },
    { from: 78,
      to: 90,
      value: 1 },
    { from: 78,
      to: 102,
      value: 1 },
    { from: 79,
      to: 99,
      value: 1 },
    { from: 80,
      to: 85,
      value: 1 },
    { from: 80,
      to: 92,
      value: 1 },
    { from: 81,
      to: 82,
      value: 1 },
    { from: 81,
      to: 94,
      value: 1 },
    { from: 81,
      to: 97,
      value: 1 },
    { from: 81,
      to: 100,
      value: 1 },
    { from: 81,
      to: 102,
      value: 1 },
    { from: 83,
      to: 85,
      value: 1 },
    { from: 84,
      to: 90,
      value: 1 },
    { from: 84,
      to: 103,
      value: 1 },
    { from: 86,
      to: 91,
      value: 2 },
    { from: 86,
      to: 100,
      value: 1 },
    { from: 88,
      to: 100,
      value: 1 },
    { from: 89,
      to: 90,
      value: 1 },
    { from: 90,
      to: 98,
      value: 1 },
    { from: 90,
      to: 100,
      value: 1 },
    { from: 90,
      to: 102,
      value: 1 },
    { from: 90,
      to: 103,
      value: 2 },
    { from: 91,
      to: 100,
      value: 2 },
    { from: 92,
      to: 99,
      value: 1 },
    { from: 94,
      to: 97,
      value: 1 },
    { from: 95,
      to: 101,
      value: 1 },
    { from: 96,
      to: 103,
      value: 1 },
    { from: 98,
      to: 102,
      value: 1 },
    { from: 99,
      to: 103,
      value: 1 },
    { from: 100,
      to: 102,
      value: 2 },
    { from: 100,
      to: 103,
      value: 1 },
    { from: 102,
      to: 103,
      value: 1 }
]);



var container = document.getElementById("mynetwork");
var data = {
  nodes: nodes,
  edges: edges
};
var options = {
  nodes: {
      shape: "dot",
      scaling: {
          customScalingFunction: function(min, max, total, value) {
              return value / total;
          },
          min: 5,
          max: 1000,
      },
      shadow: true
  },
  edges: {
    shadow: true,
    smooth: true
  },
  physics: {
    barnesHut: { gravitationalConstant: -20000 },
    stabilization: { iterations: 2500 }
  }
};

var network = new vis.Network(container, data, options);

network.on("click", function(params) {
    var node = nodes.get(params.nodes[0]);
    if (typeof node.URL != 'undefined') {
        window.open(node.URL,'_blank');
    }
});
